# AIOS Development Configuration

# Server configuration
server:
  host: "localhost"
  port: 8080
  metrics_port: 9090
  read_timeout: "15s"
  write_timeout: "15s"
  idle_timeout: "60s"

# Database configuration
database:
  host: "localhost"
  port: 5432
  name: "aios_dev"
  user: "aios"
  password: "aios_password"
  ssl_mode: "disable"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: "5m"

# Redis configuration
redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
  pool_size: 10
  min_idle_conns: 5

# AI services configuration
ai:
  ollama:
    host: "localhost"
    port: 11434
    timeout: "30s"
  models_path: "./models"
  default_model: "llama2"
  max_tokens: 2048
  temperature: 0.7

# Computer vision configuration
computer_vision:
  enabled: true
  model_path: "./models/cv"
  confidence_threshold: 0.8
  max_image_size: "10MB"

# System optimization configuration
optimization:
  enabled: true
  interval: "5m"
  cpu_threshold: 80.0
  memory_threshold: 85.0
  disk_threshold: 90.0

# Security configuration
security:
  jwt_secret: "dev-secret-key-change-in-production"
  session_timeout: "24h"
  rate_limit:
    requests_per_minute: 100
    burst: 20
  cors:
    allowed_origins: ["http://localhost:3000", "http://localhost:8082"]
    allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowed_headers: ["*"]

# Logging configuration
logging:
  level: "debug"
  format: "json"
  output: "stdout"
  file_path: "./logs/aios.log"
  max_size: "100MB"
  max_backups: 5
  max_age: 30

# Tracing configuration
tracing:
  enabled: true
  jaeger_endpoint: "http://localhost:14268/api/traces"
  service_name: "aios-daemon"
  sample_rate: 1.0

# Metrics configuration
metrics:
  enabled: true
  namespace: "aios"
  subsystem: "daemon"

# File system AI configuration
filesystem:
  watch_paths: ["/home", "/tmp"]
  ignore_patterns: [".git", "node_modules", "__pycache__"]
  analysis_interval: "10m"
  organization_enabled: true

# Desktop environment configuration
desktop:
  theme: "dark"
  ai_assistant:
    voice_enabled: true
    wake_word: "aios"
    language: "en-US"
  window_manager:
    tiling_enabled: true
    smart_gaps: true
    border_width: 2

# Development specific settings
development:
  hot_reload: true
  debug_mode: true
  profiling_enabled: true
  mock_ai_services: false
